const SAVE_CATEGORY = "SAVE_CATEGORY",
  SAVE_AMOUNT = "SAVE_AMOUNT",
  SAVE_MEDIA = "SAVE_MEDIA",
  SAVE_DETAILS = "SAVE_DETAILS",
  SAVE_BENEFICIARY = "SAVE_BENEFICIARY",
  SAVE_CHARITY = "SAVE_CHARITY",
  CREATE_CAMPAIGN = "CREATE_CAMPAIGN",
  CAMPAIGN_SUCCESS = "CAMPAIGN_SUCCESS",
  CAMPAIGN_FAILURE = "CAMPAIGN_FAILURE"

export {
  SAVE_CATEGORY,
  SAVE_AMOUNT,
  SAVE_MEDIA,
  SAVE_DETAILS,
  SAVE_BENEFICIARY,
  SAVE_CHARITY,
  CREATE_CAMPAIGN,
  CAMPAIGN_SUCCESS,
  CAMPAIGN_FAILURE
};
